version: '3'

services:
    mongoui-frontend:
        container_name: c_mongoui_frontend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '6066:6066'
        restart: unless-stopped
